name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Configure Project
        run: cmake --preset default

      - name: Package Project
        run: cpack --preset default

      - name: Upload Project as Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          path: build/SetupGo.tar.gz
          if-no-files-found: error
          overwrite: true
